### ISSUE TITLE
Lode Runner (1-4) MRA - Start Player 1 and Start Player 2 are swapped

### ISSUE THREAD

**Issue by trashuncle** [MiSTer-devel/Arcade-IremM62_MiSTer#1]
When mapping, Start Player 1 and Start Player 2 are swapped.

**Comment by Left-Empty** [comment]
For me, it seems to be only 2 to 4 with that issue, but maybe I double mapped a button without noticing it now that I think about it!
Edit: nope, you are absolutely right, it affects all four games.

**Comment by alanswx** [comment]
i think this is fixed?

**Comment by Left-Empty** [comment]
Indeed, thank you!
