### ISSUE TITLE
High res games not scaled properly in Direct Video output.

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/Arcade-IremM62_MiSTer#5]
The high resolution games (the ones with a 384x256, I am guessing, resolutions) have a wrong resolution output according to the MiSTer feedback: they are displayed as 288x255 instead, which leads to screen tearing, but also fonts to be very hard to read.

Concerned games seem to be the 4 Lode Runners, both the Spelunkers and Kid Niki Radical Ninja.

Cheers!

**Comment by paulb-nl** [comment]
Should be fixed now

**Comment by Left-Empty** [comment]
Indeed, thank you so much for all your good work, paulb!
